---
- color: d73a4a
  description: Something isn't working
  name: bug

- color: E6CF9D
  description: Work towards tech-debt
  name: chore

# Semantic Type
- name: type/major
  color: ededed
  description: ""
- name: type/minor
  color: ededed
  description: ""
- name: type/patch
  color: ededed
  description: ""

- color: 0075ca
  description: Improvements or additions to documentation
  name: documentation

- color: cfd3d7
  description: This issue or pull request already exists
  name: duplicate

- color: a2eeef
  description: New feature or request
  name: enhancement

- color: ededed
  description: ""
  name: flux/upgrade

- color: 7057ff
  description: Good for newcomers
  name: good first issue

- color: "008672"
  description: Extra attention is needed
  name: help wanted

- color: e4e669
  description: This doesn't seem right
  name: invalid

- color: 79D905
  description: Issue with CI/CD pipeline or workflow
  name: pipeline

- color: d876e3
  description: Further information is requested
  name: question

- color: ededed
  description: ""
  name: renovate/annotations

- color: ededed
  description: ""
  name: renovate/helm

- color: ededed
  description: ""
  name: renovate/image

- color: 006B75
  description: Security Issue
  name: security

- color: D93F0B
  description: Issue requires assessment
  name: triage

- color: c2e0c6
  description: Issue has been triaged
  name: triaged

- color: ffffff
  description: This will not be worked on
  name: wontfix

# Size
- name: size/XS
  color: "009900"
  description: >-
    Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: "77bb00"
  description: >-
    Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: "eebb00"
  description: >-
    Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: "ee9900"
  description: >-
    Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: "ee5500"
  description: >-
    Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: "ee0000"
  description: >-
    Denotes a PR that changes 1000+ lines, ignoring generated files.
