name = "leafybloop"
type = "webpack"
webpack_config = 'node_modules/flareact/webpack'
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-10"

[triggers]
    crons = ["0 10 0 ? * * *"]

[site]
    bucket = "./out"
    entry-point = "./"
