name = "leafybloop"
type = "webpack"
webpack_config = 'node_modules/flareact/webpack'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-10"

[triggers]
    crons = ["*/10 * * * *"]

[site]
    bucket = "./out"
    entry-point = "./"
