---
name: Deploy LeafyBloop

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        run: |
          curl -X POST ${{ secrets.CF_DEPLOY_HOOK }}
