---
name: Deploy Keycloak Theme to GHCR

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - leafybloop/*

env:
  registry:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        run: |
          curl -X POST {{ secrets.LEAFYBLOOP_DEPLOY_WEBHOOK }}
